# Generated by Django 5.2.1 on 2025-05-21 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_file',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='page_number',
        ),
        migrations.AddField(
            model_name='book',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='texts/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='age_limit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userbookstatus',
            name='status',
            field=models.CharField(choices=[('reading', 'Читаю'), ('read', 'Прочитал'), ('planned', 'В планах'), ('dropped', 'Брошено')], max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author'),
        ),
        migrations.CreateModel(
            name='ReadingDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions_rating', models.PositiveSmallIntegerField(default=1)),
                ('plot_originality', models.PositiveSmallIntegerField(default=1)),
                ('character_development', models.PositiveSmallIntegerField(default=1)),
                ('world_building', models.PositiveSmallIntegerField(default=1)),
                ('romance', models.PositiveSmallIntegerField(default=1)),
                ('humor', models.PositiveSmallIntegerField(default=1)),
                ('meaning', models.PositiveSmallIntegerField(default=1)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DiaryEntry',
        ),
    ]
